### PR TITLE
Feature/fix non blocking

### PR DESCRIPTION
**Pull request by jsmonson**
This PR removes non-blocking assignments from the combination logic and replaces them with blocking assignments in the Q_srl.v fifo. This change is beneficial because it removes the eliminates the warnings generated by pyverilog during RTL simulation for this issue.

### CODE REVIEW

**Comment by jsmonson** [comment]
@auphelia can you remind me which tests you would like me to run?

**Comment by auphelia** [comment]
Thanks @jsmonson for creating this PR! I would recommend to run at least `test_fifosizing` and `test_fpgadataflow_fifo`, but I will do that as part of the PR review as well.

**Review by preusser — APPROVED** [review]
Thanks a lot, @jsmonson!

**Comment by auphelia** [comment]
Thank you @jsmonson !

**Pull request merged**
