### PR TITLE
Feature/ultra96v2 support

### PR DESCRIPTION
**Pull request by rstar900**
Added support for Ultra96-V2 board. Tried with my own accelerator on vivado 2022.1.

### CODE REVIEW

**Comment by rstar900** [comment]
This dockerimage check is not passing. I guess it has nothing to do with my branch. It would be nice if anyone can comment on this.

**Comment by rstar900** [comment]
Update : I added my docker credentials as secrets in the branch. Hope that fixes the issue

**Comment by auphelia** [comment]
Hi @rstar900, Thank you for your PR! 
Don't worry about the dockerimage GHA not passing. I will review your PR in the next weeks and come back to you! :)

**Comment by auphelia** [comment]
Thanks @rstar900 !

**Pull request merged**
